data:
  data_root: '/data/SONICS/dataset_50k/combined_songs.csv'
  sample_rate: 24000
  duration: 60
  random_sample: True
  whisper_size: 'tiny'
  crepe_size: 'tiny'

train:
  batch_size: 8
  learning_rate: 1e-4
  weight_decay: 1e-3
  num_workers: 0
  max_epochs: 3
  precision: '16-mixed'
  accumulate_grad_batches: 4
  pin_memory: False

model:
  classifier_type: "SpecTTTra"
  feature_dim: 512
  embed_dim: 512
  num_heads: 8
  num_layers: 6
  tokenizer_clip_size: 5
  pre_norm: false
  pe_learnable: false
  pos_drop_rate: 0.0
  attn_drop_rate: 0.0
  proj_drop_rate: 0.0
  mlp_ratio: 4.0